```{r}
#install.packages("jsonlite")

library("jsonlite")
library("ggplot2")

variant_1_json <- fromJSON("./variant_1.stats.json")
variant_2_json <- fromJSON("./variant_2.stats.json")

variant_1_df <- data.frame(N = as.numeric(names(variant_1_json)),
                 ExecutionTime = unlist(variant_1_json),
                 Type = "Варіант 1",
                 stringsAsFactors = FALSE)

variant_2_df <- data.frame(N = as.numeric(names(variant_2_json)),
                 ExecutionTime = unlist(variant_2_json),
                 Type = "Варіант 2",
                 stringsAsFactors = FALSE)

comparison_df <- rbind(variant_1_df, variant_2_df)
```

Building a chart

```{r}
ggplot(comparison_df, aes(x = N, y = ExecutionTime, colour= Type))+
  geom_line()+
  geom_point()+
  ggtitle("Порівняльний графік часу виконання обох варіантів паралельної програми \nзалежно від N") +
  ylab("Час виконання, мс")+
  xlab("N")+
  labs(color = "Програма")+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 12))
```